<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <DefineConstants>$(DefineConstants);AVALONIA</DefineConstants>
    <PerfViewFolder>../PerfView</PerfViewFolder>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(PerfViewFolder)/**/*.xaml.cs">
      <Link>%(RecursiveDir)%(Filename).axaml.cs</Link>
    </Compile>

    <Compile Include="$(PerfViewFolder)/**/*.cs" 
            Exclude="$(PerfViewFolder)/**/*.g.cs;$(PerfViewFolder)/**/*.xaml.cs;$(PerfViewFolder)/App.cs" />
    
    <Compile Include="../EtwHeapDump/DotNetHeapDumper.cs" />
    <Compile Include="../EtwHeapDump/DotNetHeapDumpGraphReader.cs" />
    <Compile Include="../HeapDump/GCHeapDump.cs" />
    <Compile Include="../HeapDumpCommon/DotNetHeapInfo.cs" />
    <Compile Include="../HeapDumpCommon/GCHeapDumpNames.cs" />
    <Compile Include="../MemoryGraph/graph.cs" />
    <Compile Include="../MemoryGraph/MemoryGraph.cs" />
    <Compile Include="../Utilities/DirectoryUtilities.cs" />
    <Compile Include="../Utilities/EnvironmentUtilities.cs" />
    <Compile Include="../Utilities/FileUtilities.cs" />
    <Compile Include="../Utilities/StringUtilities.cs" />
    <Compile Include="../Utilities/SymbolsAuthenticationUtilities.cs" />
    <Compile Include="../Utilities/TeeTextWriter.cs" />
    <Compile Include="../Utilities/XmlUtilities.cs" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Azure.Core" GeneratePathProperty="true" />
    <PackageReference Include="Azure.Identity" GeneratePathProperty="true" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="MessageBox.Avalonia" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles" PrivateAssets="all" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" GeneratePathProperty="true" />
    <PackageReference Include="PerfView.SupportFiles" PrivateAssets="all" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="System.Diagnostics.EventLog" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
  </ItemGroup>

  <ItemGroup>
    <!--
    <ProjectReference Include="..\EtwClrProfilerSigning\EtwClrProfilerSigning.csproj" />
    <ProjectReference Include="..\FastSerialization\FastSerialization.csproj" />
    <ProjectReference Include="..\PerfView.Tutorial\PerfView.Tutorial.csproj" />
    -->
    <ProjectReference Include="../CSVReader/CSVReader.csproj" />
    <ProjectReference Include="../SymbolsAuth/SymbolsAuth.csproj" />
    <ProjectReference Include="../TraceEvent/TraceEvent.csproj" />
  </ItemGroup>
</Project>
